// Auto-generated by Tile — edit via the Deep Linking panel
export const linking = {
  prefixes: ['minimal-base://'],
  config: {
    screens: {
    Home: 'home',
    Settings: 'settings',
    },
  },
};
