// Auto-generated by Tile — edit via the Deep Linking panel
export const linking = {
  prefixes: ['shopifyrepo://'],
  config: {
    screens: {
    Home: 'home',
    Account: 'account',
    },
  },
};
